### ISSUE TITLE
Policy role mngt

### ISSUE THREAD

**Issue by adhorn** [awslabs/chalice#15]
I run into a lost state of the IAM role for helloworld demo, the only way I managed to get out was to log into the console and delete the existing  helloworld role in IAM. 

```
(chalice-demo) ➜  helloworld git:(master) ✗ chalice deploy
Updating IAM policy.
Traceback (most recent call last):
  File "/Users/adhorn/.virtualenvs/chalice-demo/bin/chalice", line 9, in <module>
    load_entry_point('chalice==0.0.1', 'console_scripts', 'chalice')()
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice-0.0.1-py2.7.egg/chalice/cli/__init__.py", line 161, in main
    return cli(obj={})
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice-0.0.1-py2.7.egg/chalice/cli/__init__.py", line 104, in deploy
    d.deploy(ctx.obj)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice-0.0.1-py2.7.egg/chalice/deployer.py", line 189, in deploy
    self._deploy_lambda(config)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice-0.0.1-py2.7.egg/chalice/deployer.py", line 205, in _deploy_lambda
    self._get_or_create_lambda_role_arn(config)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice-0.0.1-py2.7.egg/chalice/deployer.py", line 294, in _get_or_create_lambda_role_arn
    self._update_role_with_latest_policy(app_name, config)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice-0.0.1-py2.7.egg/chalice/deployer.py", line 310, in _update_role_with_latest_policy
    PolicyName=app_name)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore-1.4.30-py2.7.egg/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/adhorn/.virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore-1.4.30-py2.7.egg/botocore/client.py", line 572, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NoSuchEntity) when calling the DeleteRolePolicy operation: The role policy with name helloworld cannot be found.
```

**Comment by jamesls** [comment]
Closing out old issue.  This has been fixed in later versions of chalice.  Now if the role policy does not exist, we catch that exception and recreate it.
