### ISSUE TITLE
chalice deploy  ::: botocore.vendored.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by datteswararao** [awslabs/chalice#158]
I'm trying the chalice but got into the below issue for a helloworld program

created the virtual environment
verified python version (2.7)
exported proxy
exported aws_access_key_id,aws_secret_access_key,aws_session_token and aws_security_token

got into below issue: Any insights

(chalice-demo) 24a074f2d4c8:helloworld$ chalice deploy
Traceback (most recent call last):
  File "/usr/local/bin/chalice", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 283, in main
    return cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 185, in deploy
    d.deploy(config)
  File "/usr/local/lib/python2.7/site-packages/chalice/deployer.py", line 265, in deploy
    self._lambda_deploy.deploy(config)
  File "/usr/local/lib/python2.7/site-packages/chalice/deployer.py", line 556, in deploy
    if self._aws_client.lambda_function_exists(app_name):
  File "/usr/local/lib/python2.7/site-packages/chalice/awsclient.py", line 39, in lambda_function_exists
    self._client('lambda').get_function(FunctionName=name)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 274, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 314, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 356, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
(chalice-demo) 24a074f2d4c8:helloworld$

**Comment by datteswararao** [comment]
I added a default profile and got into a different issue with the roles.

botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateRole operation: User: XXXXX is not authorized to perform: iam:CreateRole on resource: XXXXX:role/helloworld

**Comment by jamesls** [comment]
The second issue is due the policy associated with that profile.  You don't have the necessary permissions needed to create an app.  You have two options:

1. If you're able to modify the policy associated with that profile, you can add the `iam:CreateRole` permission.
2. If not, you can use a pre-existing role that has sufficient permissions.  You can update the chalice config file to `{"manage_iam_role: false, "iam_role_arn": "<your role arn here>"}`.

Let me know if you have any other questions.

**Comment by datteswararao** [comment]
Looks like the 2) is going to solve my issue. I will try and let you know.

**Comment by datteswararao** [comment]
It worked. Thank you for the quick help, James.

**Comment by jamesls** [comment]
Awesome, glad to hear!
