### ISSUE TITLE
chalice new-project fails with invalid syntax

### ISSUE THREAD

**Issue by hotzen** [awslabs/chalice#191]
```
chalice new-project chalicetest
Traceback (most recent call last):
  File "/usr/local/bin/chalice", line 9, in <module>
    load_entry_point('chalice==0.5.0', 'console_scripts', 'chalice')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/chalice/cli/__init__.py", line 88
    print event['timestamp'], event['logShortId'], event['message'].strip()
              ^
SyntaxError: invalid syntax
```

**Comment by garethr** [comment]
The documentation states in the README "Note: make sure you are using python2.7". It looks from your paths like you're using Python3.5. I'd suggest grabbing a python2.7 virtualenv.

**Comment by andriisoldatenko** [comment]
I think we should add something like 
`assert sys.version_info < (3,)`
but I agree with @garethr that you should read docs first.

**Comment by jamesls** [comment]
@andriisoldatenko Are you proposing adding this to the setup.py?

**Comment by andriisoldatenko** [comment]
https://github.com/awslabs/chalice/pull/204
@jamesls

**Comment by jamesls** [comment]
Closing, #204 has been merged.
