### ISSUE TITLE
Unknown parameter in input: "contentHandling", must be one of: ...

### ISSUE THREAD

**Issue by codingjoe** [awslabs/chalice#248]
Hi there!

I stumbled upon this error. I used to work before I don't what went wrong now. I different app name too, to start clean. No luck :/

Any ideas? Did the API change?

```shell
$ chalice deploy
Updating IAM policy.
Updating lambda function...
Regen deployment package...
Sending changes to lambda.
Lambda deploy done.
API Gateway rest API already found.
Deleting root resource id
Done deleting existing resources.
Traceback (most recent call last):
  File "env/bin/chalice", line 11, in <module>
    sys.exit(main())
  File "env/lib/python2.7/site-packages/chalice/cli/__init__.py", line 298, in main
    return cli(obj={})
  File "env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "env/lib/python2.7/site-packages/chalice/cli/__init__.py", line 177, in deploy
    d.deploy(config)
  File "env/lib/python2.7/site-packages/chalice/deployer.py", line 214, in deploy
    config)
  File "env/lib/python2.7/site-packages/chalice/deployer.py", line 729, in deploy
    return self._create_resources_for_api(config, rest_api_id)
  File "env/lib/python2.7/site-packages/chalice/deployer.py", line 785, in _create_resources_for_api
    route_builder.build_resources(url_trie)
  File "env/lib/python2.7/site-packages/chalice/deployer.py", line 263, in build_resources
    self._configure_resource_route(current, http_method)
  File "env/lib/python2.7/site-packages/chalice/deployer.py", line 290, in _configure_resource_route
    self._lambda_uri()
  File "env/lib/python2.7/site-packages/chalice/deployer.py", line 896, in create_lambda_method_integration
    uri=lambda_uri,
  File "env/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "env/lib/python2.7/site-packages/botocore/client.py", line 470, in _make_api_call
    api_params, operation_model, context=request_context)
  File "env/lib/python2.7/site-packages/botocore/client.py", line 523, in _convert_to_request_dict
    api_params, operation_model)
  File "env/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "contentHandling", must be one of: restApiId, resourceId, httpMethod, type, integrationHttpMethod, uri, credentials, requestParameters, requestTemplates, passthroughBehavior, cacheNamespace, cacheKeyParameters
```

**Comment by codingjoe** [comment]
Hm... not it worked. I reinstalled boto3 and chalice.
