### ISSUE TITLE
KeyError 'random' when running deploy

### ISSUE THREAD

**Issue by colde** [awslabs/chalice#252]
After, importing random and having this line in my python code:
`randomstring = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(5))`

I know get an error like this when i run chalice deploy:
Traceback (most recent call last):
```
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/bin/chalice", line 11, in <module>
    sys.exit(main())
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/cli/__init__.py", line 339, in main
    return cli(obj={})
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/cli/__init__.py", line 218, in deploy
    d.deploy(config)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/deployer.py", line 272, in deploy
    self._lambda_deploy.deploy(config)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/deployer.py", line 637, in deploy
    self._get_or_create_lambda_role_arn(config)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/deployer.py", line 657, in _get_or_create_lambda_role_arn
    self._update_role_with_latest_policy(app_name, config)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/deployer.py", line 666, in _update_role_with_latest_policy
    app_policy = self._app_policy.generate_policy_from_app_source(config)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/deployer.py", line 570, in generate_policy_from_app_source
    app_policy = self._do_generate_from_source(config)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/deployer.py", line 580, in _do_generate_from_source
    app_policy = policy.policy_from_source_code(app_source)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/policy.py", line 20, in policy_from_source_code
    client_calls = get_client_calls_for_app(source_code)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 74, in get_client_calls_for_app
    binder = t.bind_types()
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 331, in bind_types
    self.visit(self._current_ast_namespace)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 455, in visit_Call
    self._infer_function_call(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 484, in _infer_function_call
    child_infer.bind_types()
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 331, in bind_types
    self.visit(self._current_ast_namespace)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 509, in visit_FunctionDef
    self.visit(child)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 390, in visit_Assign
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 424, in visit_Call
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 424, in visit_Call
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 404, in visit_Attribute
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 424, in visit_Call
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 404, in visit_Attribute
    self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 540, in visit
    return ast.NodeVisitor.visit(self, node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 381, in visit_Name
    self._symbol_table.get_inferred_type(node.id)
  File "/Users/loke/.virtualenvs/youbora-bi-lambda/lib/python2.7/site-packages/chalice/analyzer.py", line 241, in get_inferred_type
    symbol = self._local_table.lookup(name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/symtable.py", line 100, in lookup
    flags = self._table.symbols[name]
KeyError: 'random'
```

**Comment by stealthycoin** [comment]
It looks like with our changes to the analyzer this is no longer an issue. Please open another issue if you run into this again, or anything similar.
