### ISSUE TITLE
Error when following step in README to verify Python 2.7

### ISSUE THREAD

**Issue by edwinevans** [awslabs/chalice#275]
I get an error when running the second command to verify Python environment.

```
(chalice-demo) edwin@Edwins-MacBook-Pro-2.local:~/repo/scratch/helloworld$which python2.7
/Users/edwin/.virtualenvs/chalice-demo/bin/python2.7

(chalice-demo) edwin@Edwins-MacBook-Pro-2.local:~/repo/scratch/helloworld$virtualenv --python 
$(which python2.7) ~/.virtualenvs/chalice-demo

Running virtualenv with interpreter /Users/edwin/.virtualenvs/chalice-demo/bin/python2.7
Please use the *system* python to run this script
Traceback (most recent call last):
  File "/Users/edwin/.virtualenvs/chalice-demo/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/Users/edwin/.virtualenvs/chalice-demo/lib/python2.7/site-packages/virtualenv.py", line 713, 
in main
    symlink=options.symlink)
  File "/Users/edwin/.virtualenvs/chalice-demo/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/edwin/.virtualenvs/chalice-demo/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/edwin/.virtualenvs/chalice-demo/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Are both verification methods necessary?

**Comment by meitals** [comment]
I encountered this issue too, and it worked for me when I changed the command to `virtualenv --python /usr/local/bin/python ~/.virtualenvs/chalice-demo`.

**Comment by jamesls** [comment]
I would double check that the output of `$(which python2.7)` is returning a value.  If not, could you try using the full path to the interpreter? Similar to what meitals shows:

```
virtualenv --python /usr/local/bin/python ~/.virtualenvs/chalice-demo
```

If that's still not working, let me know and I'll reopen and take another look.
