### ISSUE TITLE
Demo deploy fails with KeyError: 'Statement'

### ISSUE THREAD

**Issue by apictogram** [awslabs/chalice#29]
On a mac running 10.11.5 or an AWS Linux machine created today, deploying the demo from a fresh install of chalice generates an exception:

```
pip install virtualenv
virtualenv ~/.virtualenvs/chalice-demo
source ~/.virtualenvs/chalice-demo/bin/activate
pip install chalice
chalice new-project helloworld
cd helloworld
chalice deploy
->

Initial creation of lambda function.
Updating IAM policy.
Traceback (most recent call last):
  File "/home/ec2-user/.virtualenvs/chalice-demo/bin/chalice", line 9, in <module>
    load_entry_point('chalice==0.0.1', 'console_scripts', 'chalice')()
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 203, in main
    return cli(obj={})
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 123, in deploy
    d.deploy(ctx.obj)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/deployer.py", line 203, in deploy
    self._deploy_lambda(config)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/deployer.py", line 218, in _deploy_lambda
    function_arn = self._first_time_lambda_create(config)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/deployer.py", line 259, in _first_time_lambda_create
    role_arn = self._get_or_create_lambda_role_arn(config)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/deployer.py", line 304, in _get_or_create_lambda_role_arn
    self._update_role_with_latest_policy(app_name, config)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/deployer.py", line 315, in _update_role_with_latest_policy
    diff = policy.diff_policies(previous, app_policy)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/policy.py", line 38, in diff_policies
    old = _create_simple_format(old)
  File "/home/ec2-user/.virtualenvs/chalice-demo/local/lib/python2.7/site-packages/chalice/policy.py", line 53, in _create_simple_format
    for statement in policy['Statement']:
KeyError: 'Statement'

```

**Comment by Funkmyster** [comment]
You need a policy file.
In my app I ended up just doing:
```bash
chalice gen-policy > .chalice/policy.json
```

**Comment by jamesls** [comment]
Oh I think I see what's happening.  In order to get `chalice deploy` to work for both initial deploys and updates, it has to check whether or not the resources it *would* create already exist.

Based on the stack trace above, it's looking for a lambda function named `helloworld`, and it appears it's found one.  Given it's a common name, I'm guessing you had created an unrelated lambda function named `helloworld` previously.

It then goes down a code path that operates under the precondition that it's done a deploy previously, which causes the exception you're seeing above (assuming it can diff the old policy with the new one;  there is no old one).

There's a couple of simliar issues/feature requests (https://github.com/awslabs/chalice/issues/32#issuecomment-232205436) that essentially boil down to the framework needing to track the exact resources it's previously created.

As an aside, I think I might need to modify the names of the resources we create to add some sort of `-chalice` suffix.

Thanks for reporting, I'll get this updated.

**Comment by apictogram** [comment]
Ah I don't think so. I saw chalice mentioned here "https://aws.amazon.com/blogs/developer/preview-the-python-serverless-microframework-for-aws/" and started off using the name 'lc-svc-marketing'. In any case I have never used the name "helloworld" before. Funny, it all works now after using your suggestion "chalice gen-policy > .chalice/policy.json" even for new functions that don't have a ".chalice/policy.json". Greate tool BTW :)

**Comment by jamesls** [comment]
Sorry, I misspoke.  It's not a duplicate lambda function, it's a duplicate role name (hello world).

**Comment by mittenchops** [comment]
Had this error initially.  It didn't seem to be auto-creating the policy. Followed it through manually adding items to the policy, ended up with the following:

```
$ chalice deploy
Updating IAM policy.
Updating lambda function...
Regen deployment package...
Sending changes to lambda.
Lambda deploy done.
API Gateway rest API already found.
Deleting root resource id
Done deleting existing resources.
Traceback (most recent call last):
  File "/usr/local/bin/chalice", line 9, in <module>
    load_entry_point('chalice==0.0.1', 'console_scripts', 'chalice')()
  File "/usr/local/lib/python2.7/dist-packages/chalice/cli/__init__.py", line 203, in main
    return cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chalice/cli/__init__.py", line 123, in deploy
    d.deploy(ctx.obj)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 204, in deploy
    rest_api_id, region_name, stage = self._deploy_api_gateway(config)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 402, in _deploy_api_gateway
    return self._create_resources_for_api(config, rest_api_id)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 469, in _create_resources_for_api
    route_builder.build_resources(url_trie)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 523, in build_resources
    self._configure_resource_route(current, http_method)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 563, in _configure_resource_route
    uri=self._lambda_uri()
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 468, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 521, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 269, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "passthroughBehavior", must be one of: restApiId, resourceId, httpMethod, type, integrationHttpMethod, uri, credentials, requestParameters, requestTemplates, cacheNamespace, cacheKeyParameters
```

Boto version 2.41.0

**Comment by dishmael** [comment]
Tried the chalice gen-policy > .chalice/policy.json but had the following error:

Initial creation of lambda function.
Updating IAM policy.

The following actions will be added to the execution policy:

logs:PutLogEvents
logs:CreateLogGroup
logs:CreateLogStream

Would you like to continue?  [Y/n]: Y
Creating deployment package.
Traceback (most recent call last):
  File "/usr/local/bin/chalice", line 9, in <module>
    load_entry_point('chalice==0.0.1', 'console_scripts', 'chalice')()
  File "/Library/Python/2.7/site-packages/chalice/cli/__init__.py", line 203, in main
    return cli(obj={})
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/chalice/cli/__init__.py", line 123, in deploy
    d.deploy(ctx.obj)
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 203, in deploy
    self._deploy_lambda(config)
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 218, in _deploy_lambda
    function_arn = self._first_time_lambda_create(config)
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 261, in _first_time_lambda_create
    config['project_dir'])
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 630, in create_deployment_package
    self._verify_has_virtualenv()
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 617, in _verify_has_virtualenv
    subprocess.check_output(['virtualenv', '--version'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Not sure what file/directory is missing.

**Comment by jamesls** [comment]
I'm able to repro the issue via https://github.com/awslabs/chalice/issues/71#issuecomment-236746131.  If I `rm -rf .chalice/venv`, rm -rf `.chalice/deployments/` and `rm -rf .chalice/policy.json`, I can get the `KeyError` for `Statement`.  This should be enough for me to work on a fix.

@mittenchops, it looks like you're using an older version of botocore.  If you run `pip install --upgrade botocore`, that should fix the issue for you.

**Comment by mittenchops** [comment]
Thanks @jamesls .  I did that update, am getting the same issue.  I don't think it's related to botocore.
