### ISSUE TITLE
"OSError: [Errno 2] No such file or directory" while running "chalice deploy"

### ISSUE THREAD

**Issue by AlexOugh** [awslabs/chalice#33]
It looks like it failed to deploy a lambda function after creating an IAM role successfully.

$ chalice deploy
Initial creation of lambda function.
Creating role
Creating deployment package.
Traceback (most recent call last):
  File "/usr/local/bin/chalice", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/chalice/cli/__init__.py", line 203, in main
    return cli(obj={})
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/chalice/cli/__init__.py", line 123, in deploy
    d.deploy(ctx.obj)
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 203, in deploy
    self._deploy_lambda(config)
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 218, in _deploy_lambda
    function_arn = self._first_time_lambda_create(config)
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 261, in _first_time_lambda_create
    config['project_dir'])
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 630, in create_deployment_package
    self._verify_has_virtualenv()
  File "/Library/Python/2.7/site-packages/chalice/deployer.py", line 617, in _verify_has_virtualenv
    subprocess.check_output(['virtualenv', '--version'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jamesls** [comment]
Thanks for reporting.  I need to update the check for checking for virtualenv.

**Comment by whatsdis** [comment]
still happening for me
