### ISSUE TITLE
chalice deploy fails with OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by whatsdis** [awslabs/chalice#67]
I looked at https://github.com/awslabs/chalice/issues/33 but wasn't clear what the fix was.

**Comment by whatsdis** [comment]
some more details (ubuntu 16.04)

vagrant@vagrant-ubuntu-trusty-64:/vagrant/hi$ chalice deploy
Initial creation of lambda function.
Creating role
Creating deployment package.
Traceback (most recent call last):
  File "/usr/local/bin/chalice", line 9, in <module>
    load_entry_point('chalice==0.0.1', 'console_scripts', 'chalice')()
  File "/usr/local/lib/python2.7/dist-packages/chalice/cli/__init__.py", line 203, in main
    return cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chalice/cli/__init__.py", line 123, in deploy
    d.deploy(ctx.obj)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 203, in deploy
    self._deploy_lambda(config)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 218, in _deploy_lambda
    function_arn = self._first_time_lambda_create(config)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 261, in _first_time_lambda_create
    config['project_dir'])
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 630, in create_deployment_package
    self._verify_has_virtualenv()
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 617, in _verify_has_virtualenv
    subprocess.check_output(['virtualenv', '--version'])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
vagrant@vagrant-ubuntu-trusty-64:/vagrant/hi$

**Comment by jamesls** [comment]
This is because I haven't done another pypi release yet so the fix for #33 isn't available in a released version.  I wanted to get a few more fixes in before the next release, so I'm not sure on the exact timeline.  Looks like there's another tracking issue for virtualenv that you're running on windows (#69), so let's track the remaining work over in that issue.

Let me know if I've missed anything.

**Comment by whatsdis** [comment]
tried this on ubuntu 16.04 OS and same thing
