### ISSUE TITLE
An error occurred (BadRequestException) when calling the CreateResource operation: Resource's path part must be specified

### ISSUE THREAD

**Issue by alexissmirnov** [awslabs/chalice#76]
Trying out the tutorial. 

this works fine:
```
@app.route('/')
def index():
    return {'hello': 'world'}
```

this:

```
@app.route('/')
def index():
    return {'hello': 'world'}

@app.route('/introspect/')
def introspect():
    return app.current_request.to_dict()
```

returns the following:

```
chalice deploy
Updating IAM policy.
Updating lambda function...
Regen deployment package...
Sending changes to lambda.
Lambda deploy done.
API Gateway rest API already found.
Deleting root resource id
Done deleting existing resources.
Traceback (most recent call last):
  File "/usr/local/bin/chalice", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/chalice/cli/__init__.py", line 203, in main
    return cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chalice/cli/__init__.py", line 123, in deploy
    d.deploy(ctx.obj)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 204, in deploy
    rest_api_id, region_name, stage = self._deploy_api_gateway(config)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 402, in _deploy_api_gateway
    return self._create_resources_for_api(config, rest_api_id)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 469, in _create_resources_for_api
    route_builder.build_resources(url_trie)
  File "/usr/local/lib/python2.7/dist-packages/chalice/deployer.py", line 513, in build_resources
    pathPart=current['name']
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 572, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (BadRequestException) when calling the CreateResource operation: Resource's path part must be specified
```

**Comment by jamesls** [comment]
This was fixed recently, but I haven't published a release yet.  I'm hoping to get a release out soon, there's just a few more bug fixes I want to include.
