### ISSUE TITLE
chalice logs don't use the profile seted

### ISSUE THREAD

**Issue by molleda** [awslabs/chalice#99]
I have some profiles in my laptop, for chalice I use one specific profile and this is setted in the .chalice/config.json but when I use chalice logs I can see a error like this:

```python
(chalice-accounts)user@Jugger ~/git/chalice/chalice-demo (master) $ chalice logs
Traceback (most recent call last):
  File "/Users/user/virtualenvs/chalice-demo/bin/chalice", line 11, in <module>
    sys.exit(main())
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice/cli/__init__.py", line 223, in main
    return cli(obj={})
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice/cli/__init__.py", line 170, in logs
    show_lambda_logs(ctx.obj, num_entries, include_lambda_messages)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice/cli/__init__.py", line 60, in show_lambda_logs
    for event in events:
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/chalice/logs.py", line 79, in retrieve_logs
    interleaved=True):
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/client.py", line 561, in _make_api_call
    operation_model, request_dict)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/endpoint.py", line 142, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/endpoint.py", line 126, in create_request
    operation_name=operation_model.name)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/signers.py", line 147, in sign
    auth.add_auth(request)
  File "/Users/user/virtualenvs/chalice-demo/lib/python2.7/site-packages/botocore/auth.py", line 314, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by jamesls** [comment]
Fixed via https://github.com/awslabs/chalice/pull/100
